/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { UserVerification } from "./UserVerification";
import { UserVerificationCountArgs } from "./UserVerificationCountArgs";
import { UserVerificationFindManyArgs } from "./UserVerificationFindManyArgs";
import { UserVerificationFindUniqueArgs } from "./UserVerificationFindUniqueArgs";
import { DeleteUserVerificationArgs } from "./DeleteUserVerificationArgs";
import { UserVerificationService } from "../userVerification.service";
@graphql.Resolver(() => UserVerification)
export class UserVerificationResolverBase {
  constructor(protected readonly service: UserVerificationService) {}

  async _userVerificationsMeta(
    @graphql.Args() args: UserVerificationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [UserVerification])
  async userVerifications(
    @graphql.Args() args: UserVerificationFindManyArgs
  ): Promise<UserVerification[]> {
    return this.service.userVerifications(args);
  }

  @graphql.Query(() => UserVerification, { nullable: true })
  async userVerification(
    @graphql.Args() args: UserVerificationFindUniqueArgs
  ): Promise<UserVerification | null> {
    const result = await this.service.userVerification(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UserVerification)
  async deleteUserVerification(
    @graphql.Args() args: DeleteUserVerificationArgs
  ): Promise<UserVerification | null> {
    try {
      return await this.service.deleteUserVerification(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
