/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ReferralUse } from "./ReferralUse";
import { ReferralUseCountArgs } from "./ReferralUseCountArgs";
import { ReferralUseFindManyArgs } from "./ReferralUseFindManyArgs";
import { ReferralUseFindUniqueArgs } from "./ReferralUseFindUniqueArgs";
import { DeleteReferralUseArgs } from "./DeleteReferralUseArgs";
import { ReferralUseService } from "../referralUse.service";
@graphql.Resolver(() => ReferralUse)
export class ReferralUseResolverBase {
  constructor(protected readonly service: ReferralUseService) {}

  async _referralUsesMeta(
    @graphql.Args() args: ReferralUseCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ReferralUse])
  async referralUses(
    @graphql.Args() args: ReferralUseFindManyArgs
  ): Promise<ReferralUse[]> {
    return this.service.referralUses(args);
  }

  @graphql.Query(() => ReferralUse, { nullable: true })
  async referralUse(
    @graphql.Args() args: ReferralUseFindUniqueArgs
  ): Promise<ReferralUse | null> {
    const result = await this.service.referralUse(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ReferralUse)
  async deleteReferralUse(
    @graphql.Args() args: DeleteReferralUseArgs
  ): Promise<ReferralUse | null> {
    try {
      return await this.service.deleteReferralUse(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
